package tessellate

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/primandproper/beeline/internal/beeline"

	"github.com/uber/h3-go/v4"
)

// Mask is the design's road-mask (§7): the set of H3 cells an operator's road
// layer says actually contain roads, at a fixed resolution. Seed intersects the
// geometric area disk with this set so cells with no road network (ocean, open
// water, roadless park interior) never enter the pair set. It is operator-supplied
// data for a given region — see cmd/tools/maskgen, which derives it from Overture.
//
// A nil *Mask means "no mask": Seed keeps every cell (the prototype's original
// behavior). The mask is resolution-specific because its cell IDs only mean
// anything at Resolution; Seed applies it only when the area resolution matches.
type Mask struct {
	cells      map[beeline.H3Cell]struct{}
	Resolution int
}

// NewMask builds a Mask over the given cells at the given resolution. It is used
// by the mask-builder tool (cmd/tools/maskgen) and in tests; the runtime loads a
// mask from disk with LoadMask instead.
func NewMask(resolution int, cells []beeline.H3Cell) *Mask {
	set := make(map[beeline.H3Cell]struct{}, len(cells))
	for _, c := range cells {
		set[c] = struct{}{}
	}

	return &Mask{cells: set, Resolution: resolution}
}

// Len reports how many road cells the mask holds.
func (m *Mask) Len() int {
	if m == nil {
		return 0
	}

	return len(m.cells)
}

// Allows reports whether a cell at resolution cellRes should be kept — i.e. it has
// road coverage according to the mask. The mask stores cells at m.Resolution, and
// answers other resolutions through the H3 hierarchy so a single mask survives a
// runtime resolution change from the console:
//
//   - cellRes == m.Resolution: direct membership.
//   - cellRes  >  m.Resolution (finer cells): the cell inherits its ancestor's
//     coverage. This is approximate near shorelines — every child of a road-bearing
//     parent is kept even if it is water — so the pruned edge is only as sharp as
//     m.Resolution. Rebuild the mask at cellRes (`make mask MASK_RESOLUTION=…`) for a
//     crisp edge at that zoom.
//   - cellRes  <  m.Resolution (coarser cells): kept if any descendant has roads.
//
// On any H3 error it fails open (keeps the cell) rather than dropping real area.
func (m *Mask) Allows(cell beeline.H3Cell, cellRes int) bool {
	switch {
	case cellRes == m.Resolution:
		_, ok := m.cells[cell]

		return ok
	case cellRes > m.Resolution:
		ancestor, err := cell.Parent(m.Resolution)
		if err != nil {
			return true
		}
		_, ok := m.cells[ancestor]

		return ok
	default:
		descendants, err := cell.Children(m.Resolution)
		if err != nil {
			return true
		}
		for _, d := range descendants {
			if _, ok := m.cells[d]; ok {
				return true
			}
		}

		return false
	}
}

// Write serializes the mask to w in the format LoadMask reads: a header comment,
// the `resolution <n>` line, then one cell ID per line sorted lexically so the
// artifact diffs cleanly in git.
func (m *Mask) Write(w io.Writer) error {
	lines := make([]string, 0, len(m.cells)+2)
	lines = append(lines,
		"# beeline road mask (§7): H3 cells with road coverage. Generated by `make mask`.",
		fmt.Sprintf("resolution %d", m.Resolution),
	)
	for c := range m.cells {
		lines = append(lines, c.String())
	}
	sort.Strings(lines[2:])

	bw := bufio.NewWriter(w)
	for _, line := range lines {
		if _, err := fmt.Fprintln(bw, line); err != nil {
			return fmt.Errorf("tessellate: writing road mask: %w", err)
		}
	}

	return bw.Flush()
}

// LoadMask reads a mask file produced by `make mask` (cmd/tools/maskgen). The
// format is line-oriented and diff-friendly: blank lines and `#` comments are
// ignored, a single `resolution <n>` header declares the cells' resolution, and
// every remaining line is one H3 cell ID (lowercase hex, as h3.Cell.String
// emits). Callers that treat "no mask configured" as valid should guard on an
// empty path before calling; LoadMask always returns a mask or an error.
func LoadMask(path string) (mask *Mask, err error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("tessellate: opening road mask %q: %w", path, err)
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = fmt.Errorf("tessellate: closing road mask %q: %w", path, cerr)
		}
	}()

	mask = &Mask{cells: make(map[beeline.H3Cell]struct{}), Resolution: -1}

	scanner := bufio.NewScanner(f)
	for line := 1; scanner.Scan(); line++ {
		text := strings.TrimSpace(scanner.Text())
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}

		if res, ok := strings.CutPrefix(text, "resolution "); ok {
			parsed, convErr := strconv.Atoi(strings.TrimSpace(res))
			if convErr != nil {
				return nil, fmt.Errorf("tessellate: road mask %q line %d: bad resolution %q: %w", path, line, res, convErr)
			}
			mask.Resolution = parsed

			continue
		}

		cell := h3.CellFromString(text)
		if !cell.IsValid() {
			return nil, fmt.Errorf("tessellate: road mask %q line %d: invalid H3 cell %q", path, line, text)
		}
		mask.cells[cell] = struct{}{}
	}
	if scanErr := scanner.Err(); scanErr != nil {
		return nil, fmt.Errorf("tessellate: reading road mask %q: %w", path, scanErr)
	}

	if mask.Resolution < 0 {
		return nil, fmt.Errorf("tessellate: road mask %q is missing its `resolution <n>` header", path)
	}

	return mask, nil
}
