package main

import (
	"time"

	"github.com/primandproper/beeline/internal/config"

	"github.com/primandproper/platform-go/v4/observability"
	"github.com/primandproper/platform-go/v4/observability/logging"
	loggingcfg "github.com/primandproper/platform-go/v4/observability/logging/config"
	serverhttp "github.com/primandproper/platform-go/v4/server/http"
)

// Each builder returns a fully-formed *config.Config for one environment. The
// configs are constructed here as real, typed Go objects — the compiler and the
// config's own Validate method are the guardrails — and then Render projects
// them to the JSON files under config/. Grow a builder as the application's
// Config grows (database, HTTP server, real telemetry, ...); the leftover
// observability pillars (tracing, metrics, profiling) stay at their zero values,
// which platform-go resolves to noop providers.

// austin is the demo service-area center shared by both environments: Lake Travis,
// the wide reservoir in the Austin, TX metro. It is chosen so road-aware
// tessellation is visible — at resolution 9 roughly a quarter of the area disk is
// open water with no roads, which the mask prunes, so the operator console shows
// the lake carved out instead of a solid hexagon. (Dense urban Austin is fully
// road-covered and would prune almost nothing.) Its road mask lives at
// config/masks/austin-res9.cells (built at this resolution by `make mask`).
var austin = config.AreaConfig{
	Lat:         30.34284460447388,
	Lng:         -98.02736352689148,
	Resolution:  9,
	AreaRings:   14,
	RadiusRings: 3,
}

// austinRoadMask is the road mask matching the austin area, generated by
// `make mask`. See design §7 (road-aware tessellation).
const austinRoadMask = "config/masks/austin-res9.cells"

// defaultProfiles are the routing modes and their constant speeds (m/s) the
// Haversine engine uses.
func defaultProfiles() map[string]float64 {
	return map[string]float64{
		"car":  13.9, // ~50 km/h
		"bike": 4.2,  // ~15 km/h
		"walk": 1.4,  // ~5 km/h
	}
}

// buildLocalDevConfig is the config a developer runs against locally: structured
// slog logging at debug, and a short freshness TTL so the debt signal moves quickly
// while iterating.
func buildLocalDevConfig() *config.Config {
	return &config.Config{
		Observability: observability.Config{
			Logging: loggingcfg.Config{
				Provider:    loggingcfg.ProviderSlog,
				ServiceName: config.DefaultServiceName,
				Level:       logging.DebugLevel,
			},
		},
		Matrix: config.MatrixConfig{
			Server: serverhttp.Config{
				Port:            8080,
				StartupDeadline: 5 * time.Second,
			},
			Area:           austin,
			RoadMaskPath:   austinRoadMask,
			Profiles:       defaultProfiles(),
			DefaultProfile: "car",
			TargetTTL:      30 * time.Second,
			LeaseDuration:  15 * time.Second,
			RefreshWorkers: 4,
			RefreshBatch:   256,
		},
	}
}

// buildProductionConfig is the config for a production deployment: the same
// structured slog logging dialed back to info, a longer freshness TTL, and more
// refresh workers to keep the working set fresh at scale.
func buildProductionConfig() *config.Config {
	return &config.Config{
		Observability: observability.Config{
			Logging: loggingcfg.Config{
				Provider:    loggingcfg.ProviderSlog,
				ServiceName: config.DefaultServiceName,
				Level:       logging.InfoLevel,
			},
		},
		Matrix: config.MatrixConfig{
			Server: serverhttp.Config{
				Port:            8080,
				StartupDeadline: 5 * time.Second,
			},
			Area:           austin,
			RoadMaskPath:   austinRoadMask,
			Profiles:       defaultProfiles(),
			DefaultProfile: "car",
			TargetTTL:      300 * time.Second,
			LeaseDuration:  60 * time.Second,
			RefreshWorkers: 8,
			RefreshBatch:   512,
		},
	}
}
