// Package sqlite is the persistent store for operator-configured service areas. It
// backs the control plane's area registry with an embedded SQLite database
// (modernc.org/sqlite, pure Go — no cgo), so a single self-hostable binary keeps its
// areas across restarts. Typed queries are generated by sqlc into the generated
// subpackage; this package wraps them in an area-oriented repository and owns schema
// migration.
package sqlite

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"io/fs"

	"github.com/pressly/goose/v3"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// migrate applies all pending schema migrations to db over the embedded migration
// files. It uses goose's instance-based Provider (not the package-global Up/SetDialect
// functions) so concurrent opens — e.g. parallel tests, each with its own database —
// don't race on shared goose state. It is idempotent: applied migrations are skipped.
func migrate(db *sql.DB) error {
	sub, err := fs.Sub(migrationFS, "migrations")
	if err != nil {
		return fmt.Errorf("sqlite: locating migrations: %w", err)
	}

	provider, err := goose.NewProvider(goose.DialectSQLite3, db, sub)
	if err != nil {
		return fmt.Errorf("sqlite: building migration provider: %w", err)
	}

	if _, err = provider.Up(context.Background()); err != nil {
		return fmt.Errorf("sqlite: applying migrations: %w", err)
	}

	return nil
}
