// Package sqlite is the persistent store for operator-configured service areas. It
// backs the control plane's area registry with an embedded SQLite database
// (modernc.org/sqlite, pure Go — no cgo), so a single self-hostable binary keeps its
// areas across restarts. Typed queries are generated by sqlc into the generated
// subpackage; this package wraps them in an area-oriented repository and owns schema
// migration.
package sqlite

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"io/fs"

	"github.com/primandproper/platform-go/v7/database/migrate"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// runMigrations applies all pending schema migrations to db over the embedded
// migration files. The platform migrator is instance-based (not goose's
// package-global state), so concurrent opens — e.g. parallel tests, each with its
// own database — don't race. No lock is taken: the SQLite dialect has no advisory
// locking, and each database here has exactly one opener. It is idempotent:
// applied migrations are skipped.
func runMigrations(db *sql.DB) error {
	sub, err := fs.Sub(migrationFS, "migrations")
	if err != nil {
		return fmt.Errorf("sqlite: locating migrations: %w", err)
	}

	migrator, err := migrate.New(migrate.DialectSQLite, sub)
	if err != nil {
		return fmt.Errorf("sqlite: building migrator: %w", err)
	}

	if err = migrator.Migrate(context.Background(), db); err != nil {
		return fmt.Errorf("sqlite: applying migrations: %w", err)
	}

	return nil
}
